[server]
port = 8080

[location]
# Geographical location
# location in sexigesimal degrees
lat = '60:11:37'
lon = '-1:17:40'

# location specific configuration
# for weather forecasting
[metoffice]
inshore_area = "iw18"
station_id = "353917" 
shipping_area = "Fair Isle" 
region = "os" 
region_id = "500"

[images]
# key:value pairs, indicating a "local name" for a file, 
# and the corresponding URL it should be fetched from
# this will be cached automatically, and expired as on a regular basis (e.g. every 4 hours)
"solar_image.jpg" = {url="https://sdo.gsfc.nasa.gov/assets/img/latest/f_211_193_171pfss_1024.jpg", width=1024, height=1024}
"aurora_prediction.jpg" = {url="http://services.swpc.noaa.gov/images/animations/ovation-north/latest.jpg", width=800, height=800}
